apiVersion: v1
kind: Service
metadata:
  name: health-app-service
spec:
  type: LoadBalancer
  selector:    
    app: my-health-app  
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP