apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-health-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-health-app
    spec:
      containers:
      - name: my-health-app
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        # image: REGISTRY/REPO:TAG
        # The full image will be dynamically added by Kustomize in the workflow.
        image: image-placeholder
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
                name: mssql-secret
                key: db-connection-string-secret
      terminationGracePeriodSeconds: 120