apiVersion: v1
kind: Secret
metadata:
  name:  mssql-secret
data:
   db-connection-string-secret: U2VydmVyPXRjcDptaGMtc3FsO0luaXRpYWwgQ2F0YWxvZz1taGNkYjtQZXJzaXN0IFNlY3VyaXR5IEluZm89RmFsc2U7VXNlciBJRD1zYTtQYXNzd29yZD1QYVNTdzByZDMyMTtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=
type: Opaque
