name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2   

    - name: SonarCloud Scan js and html
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: SonarCloud Scan C#
      uses: Secbyte/dotnet-sonarscanner@v2.2
      with:
        buildCommand: dotnet build MHC_ASPNetCore.sln 
        projectKey: myhealthinternalcsharp
        projectName: myhealthinternal
        sonarOrganisation: computerenterprisesinc
        beginArguments: >
          /d:sonar.projectBaseDir="../"
          /d:sonar.project.settings=""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
    - name: docker build
      run: docker build

