name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2   

    - name: SonarCloud Scan js and html
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SCAN_PULL_REQUEST: true

    # The sonar prop files interferes with the .net sonar scanner
    - name: cleanup sonar props file 
      run: rm sonar-project.properties

    - name: SonarCloud Scan C#
      uses: Secbyte/dotnet-sonarscanner@v2.2
      with:
        buildCommand: dotnet build MHC_ASPNetCore.sln 
        projectKey: myhealthinternalcsharp
        projectName: myhealthinternal
        sonarOrganisation: computerenterprisesinc
        beginArguments: >
          /d:sonar.projectBaseDir="../"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
    - name: docker build
      run: docker build

